[package]
name = "prototyping"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies]
deno_core = "0.188.0"
serde_v8 = "0.99.0"
serde_json = "1.0.96"
tree-sitter = "0.20.10"

[build-dependencies]
cc="*"
