[package]
name = "core"
version = "0.1.0"
edition = "2021"



[dependencies]
deno_core = "0.189.0"
serde_v8 = "0.100.0"
serde_json = "1.0.96"
tree-sitter = "0.20.10"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
cc="*"
