on: push
name: Check Code
jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout tree-sitter JavaScript
        run: git clone https://github.com/tree-sitter/tree-sitter-javascript.git
      - name: Checkout tree-sitter Python
        run: git clone https://github.com/tree-sitter/tree-sitter-python.git
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
            default: true
      - name: Check code with Clippy
        run: cargo clippy
      - name: Check formatting
        run: cargo fmt --check
